---
author:
  - 'Jean-Sébastien Pédron <jean-sebastien@yakaz.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: erlsvc
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Class::Inspector: 0
  Exception::Class: 0
  Exception::Class::TryCatch: 0
  File::ShareDir: 0
  Getopt::Long::Descriptive: 0
  YAML::Tiny: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 1.00
